### ISSUE TITLE
Crashed phone / Built for older versions of Android

### ISSUE THREAD

**Issue by vertigo220** [rparkins999/CalendarTrigger#24]
I'm combining these separate issues because I suspect they're connected. I just added a class and about a second or two after getting to the next screen, my phone completely crashed, and a couple seconds later was rebooting. I wasn't even aware an app could do this on Android. Anyways, I could be wrong, but I can't help but think it may be because when first launching the app, due to it being targeted toward older versions of Android, it requested all permissions immediately instead of as they're needed, and I of course disabled all but calendars and notifications, since that's all it seems the app should need to accomplish it's purpose. So it would be ideal to update it to target newer versions to avoid this and hopefully prevent crashing. Until then, I unfortunately can't use it.

**Comment by rparkins999** [comment]
As you say, an app can't crash your phone, at least if it isn't rooted. If your phone crashes, there is something wrong with the phone itself or with its version of Android. I see no justification for blaming the app that you happen to have been interacting with at the time unless the crash is reproducible every time you run the app. On any normally configured phone, there will be lots of system apps, and possibly other apps that you have installed, running foreground or background servers which can become active at any time: if an app can crash the phone, any of those could be responsible. I have been running CalendarTrigger for many years on several different phones. None of my phones has ever crashed.

Anyway if you are not simply being abusive and seriously expecting me to do anything about it, you need to provide some context. What kind of phone are you using? What Android version is it running? What other apps are active? What did CalendarTrigger's log say (the README.md will tell you how to enable logging)?

At the end of README.md there is a list of permissions that CalendarTrigger uses, why it uses them, and what parts of its functionality won't work if particular permissions are denied. If you deny all but calendars and notifications, there isn't much point in using it at all. It won't do anything that you can't equally well do with reminders in your calendar. If you can't be bothered to read the documentation, I'm not surprised that you can't use it. That isn't very useful information to me or anyone else who looks at this project.

As to targeting an old version of Android, this is because newer versions deny access to a broadcast message which CalendarTrigger uses. I'm not interested in changing that because I need the functionality that it provides. Google have an annoying habit of removing things without providing a viable alternative.

**Comment by vertigo220** [comment]
I was reading through the documentation as I was going, until my phone crashed, which never happens. It's not unreasonable to assume that a phone that never crashes _might_ have crashed because of an app I was using for the first time, and that was denied permissions, which often causes apps themselves to crash. To assume that I'm "being abusive" because I'm bringing this to your attention and hoping for confirmation and a fix (in the event that's what caused the crash) says a lot about you. As for permissions, I'm not going to read all the way through that long README without even knowing if the app can do what I want, and as I said, I made it up to a certain point before it crashed. If you're going to read the entire manual for every car you look to buy before even test-driving it, you're going to be car shopping for a while, and expecting people to do so is unreasonable.

You also very defensively state that an app can't crash the phone, claiming it can't be responsible, then state that if I want you to do anything about it I'd need to provide x, y, and z. How could you do something about it if it's impossible it could have caused the crash? So reading through the entire README and enabling logging and providing all that info would be toward what purpose, exactly?

And since all I wanted was to try the calendar notification capabilities, those are indeed all the permissions I need. If you want people to read about the permissions and know why the app asks for them in the way it does, maybe you should put that part at the TOP of the README, so it's first, like the permissions requests are when launching the app, not last. And based on your overly defensive response, I feel even less inclined to provide it with other permissions, or even those. I doubt I'm missing much without this app, and you even said so yourself, so I'll just uninstall and move on.
